version: '3'
services:

#  front:
#    container_name: front
#    build:
#      context: .
#      dockerfile: ./snaplook-frontend/Dockerfile
#    restart: on-failure
#    ports:
#      - '3000:3000'

  db:
    container_name: db
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

  snaplook:
    container_name: snaplook
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8444
    ports:
      - "8444:8444"
    environment:
      OPENAI_API_KEY_SNAPLOOK: sk-proj-jRKGH5SgNyMvuKPkRz3MT3BlbkFJ9n1UknvcU80zePpEOhgN













