"""add all

Revision ID: a17f953a5d32
Revises: 
Create Date: 2024-07-11 11:00:00.997693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a17f953a5d32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tarif',
    sa.Column('name', postgresql.ENUM('FREE', 'PRIVATE', 'PRO', name='tariftype'), nullable=False),
    sa.Column('limit_urls_per_month', sa.Integer(), nullable=False),
    sa.Column('limit_images_per_month', sa.Integer(), nullable=False),
    sa.Column('price_per_month', sa.Integer(), nullable=False),
    sa.Column('price_per_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Users',
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('telegram', sa.BigInteger(), nullable=True),
    sa.Column('yandex', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('limit_urls', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('tarif_of_user', postgresql.ENUM('FREE', 'PRIVATE', 'PRO', name='tariftype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Tarif')
    # ### end Alembic commands ###
